### ISSUE TITLE
Solarized Dark Chandrian snippet tabstops are nearly invisible

### ISSUE THREAD

**Issue by zanedp** [JackKenney/solarized-chandrian-theme#2]
As seen in this image, the snippet tabstop in Solarized Dark Chandrian can barely be discerned. It's nearly impossible to tell that typing will replace the word `value`.
![image](https://user-images.githubusercontent.com/295055/208134933-36856007-1def-46f8-8779-68b3332e5222.png)

Using `"editor.snippetTabstopHighlightBackground": "#586e75"` is much more visible:
![image](https://user-images.githubusercontent.com/295055/208136004-9127dc2a-b33e-4f2f-9eee-020ad1e96765.png)

**Comment by JackKenney** [comment]
Thanks @zanedp! Should be all set. Available in release 2.0.15
