### ISSUE TITLE
Solarized Dark Chandrian: icon on discussion during live share is not visible

### ISSUE THREAD

**Issue by zanedp** [JackKenney/solarized-chandrian-theme#3]
It was not obvious to me what this was because the + sign was not visible:
![image](https://user-images.githubusercontent.com/295055/208181344-8720c834-b042-4519-a9f1-6f7e181bce2e.png)

Using `"editorGutter.commentRangeForeground": "#85A930"` works well:
![image](https://user-images.githubusercontent.com/295055/208182215-6755e044-1d45-46ec-a577-54c00cd0b2de.png)

**Comment by JackKenney** [comment]
Thanks @zanedp! Should be all set. Available in release 2.0.15
